// import runtime from 'serviceworker-webpack-plugin/lib/runtime';
import image from './image.jpg';
import 'normalize.css';
import './theme.css';

class App {
  constructor() {
    console.log('🦄application is running...');

    /**
     * Adding and Image to the content of the page
     */
    const imageWrapper = document.getElementsByClassName('image-wrapper')[0];
    const myImage = new Image();
    myImage.src = image;
    myImage.alt = 'some random image';
    imageWrapper.appendChild(myImage);
  }
}

window.addEventListener('load', () => {
  if ('serviceWorker' in navigator) {
    // initiating the service-worker generated by workbox-webpack-plugin
    navigator.serviceWorker.register('/service-worker.js');
  } else {
    console.info('this browser cannot use service workers');
  }

  new App();
});
